# Generated by Django 5.0 on 2025-11-12 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehistory',
            name='service_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.servicecenter'),
        ),
        migrations.AlterField(
            model_name='servicestatus',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='vehicle.servicebooking'),
        ),
        migrations.AlterField(
            model_name='servicestatus',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
